# Site settings
title: Jack Morrison
email: 901jackmorrison@gmail.com
url: https://jack-morrison.github.io
description: "High-Performance Computing Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Jack Morrison

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jack-morrison
  - title: linkedin
    url: https://www.linkedin.com/in/jackcmorrison/


# Build settings
markdown: kramdown
permalink: pretty
